/*
 * @Author: yulinZ 1973329248@qq.com
 * @Date: 2022-12-09 14:06:42
 * @LastEditors: yulinZ 1973329248@qq.com
 * @LastEditTime: 2022-12-09 15:50:38
 * @FilePath: \-vue3-vite-element-plus-electron-tailwindcss\components.d.ts
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElButtonGroup: typeof import("element-plus/es")["ElButtonGroup"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTimePicker: typeof import("element-plus/es")["ElTimePicker"];
    ElUpload: typeof import("element-plus/es")["ElUpload"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    ImagePreview: typeof import("./src/components/imagePreview/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    UploadImg: typeof import("./src/components/uploadImg/index.vue")["default"];
    ZTable: typeof import("./src/components/ZTable/ZTable.vue")["default"];
  }
}
